config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }

  resources :articles
  resources :comments
  
  root 'articles#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)

    user ||= User.new

    if user.role? :admin
        can :manage, :all
    else
        can :read, Article
        can [:update, :destroy], Comment do |comment|
            comment.user == user
        end
        can :create, Comment if user.id
    end

    if user.role? :author
        can :create, Article
        can [:update, :destroy], Article do |article|
            article.user == user
        end
    end 

    



    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :user
  has_many :comments, dependent: :destroy

  validates :title, presence: true

  def html
    renderer = Redcarpet::Render::HTML.new(render_options = {})
    markdown = Redcarpet::Markdown.new(renderer, extensions = {})
    markdown.render(self.content).html_safe
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base

belongs_to :user
belongs_to :article

validates :content, presence: true

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def role?(role_to_compare)
    self.role.to_s == role_to_compare.to_s
  end

  scope :author, -> { where(role: "author") | where(role: "admin") }

  validates :name, presence: true

  has_many :articles
  has_many :comments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_path, alert: "ERROR: You do not have permission to perform that action."
  end
  
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

before_action :authenticate_user!, except: [:index, :show]
load_and_authorize_resource

def index 
  @articles = Article.all
end

def new
  @article = Article.new
end

def create
  article = Article.create(article_params)
  article.update(user_id: current_user.id)
  redirect_to articles_path
end

def edit
  @article = Article.find(params[:id]) 
end

def update
  article = Article.find(params[:id])
  article.update(article_params)
  if current_user.role?("admin")
  article.update(params.require(:article).permit(:title, :content, :image, :user_id))
  end
  redirect_to article_path(article)
end

def show
  @article = Article.find(params[:id])
  @comment = Comment.new
end

def destroy
  article = Article.find(params[:id])
  article.destroy
  redirect_to(articles_path)
end

private

def article_params
  params.require(:article).permit(:title, :content, :image)
end




end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

before_action :authenticate_user!
load_and_authorize_resource

def create
  comment = Comment.create(comment_params)
  comment.update(user_id: current_user.id)
  redirect_to article_path(params['comment']['article_id'])
end

def edit
  @comment = Comment.find(params[:id]) 
end

def update
  comment = Comment.find(params[:id])
  comment.update(comment_params)
  redirect_to article_path(comment.article_id)
end

def destroy
  comment = Comment.find(params[:id])
  article_id = comment.article_id
  comment.destroy
  redirect_to article_path(article_id)
end

private

def comment_params
  params.require(:comment).permit(:content, :article_id)
end




end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :current_password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/edit.html.erb
<h1>Edit Article</h1>

<%= form_for @article do |f| %>

<% if current_user.role?("admin") %>
<%= f.label :user_id, 'Author' %>
<%= f.select :user_id, User.author.collect { |u| [ u.name, u.id ] } %>
<br><br>
<% end %>

<%= f.label :title %><br>
<%= f.text_field :title %><br>

<%= f.label :content %><br>
<%= f.text_area :content %><br>

<%= f.label :image %><br>
<%= f.text_field :image %><br>

<%= f.submit 'Edit Article' %>


<% end %>

app/views/articles/index.html.erb
<h1>Index</h1>

<% if can? :create, Article %>
<%= link_to('New Article', new_article_path, class: 'new') %><br><br><br>
<% end %>

<% @articles.each do |article| %>

<%= link_to(article.title, article_path(article)) %>

<br><br>
<% end %>

app/views/articles/new.html.erb
<h1>Write New Article</h1>

<%= form_for @article do |f| %>

<%= f.label :title %><br>
<%= f.text_field :title, autofocus: true %><br>

<%= f.label :content %><br>
<%= f.text_area :content, rows: 15 %><br>

<%= f.label :image %><br>
<%= f.text_field :image, placeholder: 'Optional image URL' %><br>

<%= f.submit 'New Article' %>

<% end %>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>

<p>
<% if @article.user %>
by <%= @article.user.name %>
<% end %><br><br>

<% if @article.image != "" %>
  <%= image_tag(@article.image) %><br><br>
<% end %>

  <%= @article.html %>
</p>
<p>
  <% if can? :update, @article %>
  <%= link_to 'Edit', edit_article_path(@article) %>
  <% end %>
  <% if can? :destroy, @article %>
  - <%= link_to 'Delete', article_path(@article), method: :delete, data: {confirm: 'Are you sure you want to delete this article?'} %>
  <% end %>
</p>


<br>
<section class="comment_section">
<h3>Comments</h3>
<% @article.comments.each do |comment| %>
<div class="comment">
<h4><%= comment.user.name %> - <%= comment.updated_at.strftime("%H:%M, %e %b %Y") %></h4><br>
<%= comment.content %> <br><br>
<% if can? :update, comment %>
<%= link_to 'Edit', edit_comment_path(comment) %>
<% end %>
<% if can? :destroy, comment %>
- <%= link_to 'Delete', comment_path(comment), method: :delete, data: {confirm: 'Are you sure you want to delete this comment?'} %><br>
</div>
<% end %>

<br>

<% end %>

<% if current_user %>
<h3>Write a comment:</h3> 
<%= form_for @comment do |f| %>
<%= f.hidden_field :article_id, value: @article.id %>
<%= f.text_area :content, rows: 5 %>
<br>
<%= f.submit %>

<% end %>
<% end %>

</section>

app/views/comments/edit.html.erb
<h3>Edit your comment:</h3> 
<%= form_for @comment do |f| %>
<%= f.text_area :content %>
<br>
<%= f.submit %>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WikiCode</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='https://fonts.googleapis.com/css?family=Jura:400,600' rel='stylesheet' type='text/css'>
</head>
<body>
<header>
<div class='login'>
<% if current_user %>
<%= "Hi, #{current_user.name}!" %>
<%= link_to 'Log Out', destroy_user_session_path, method: :delete %>
<%= link_to 'Edit Details', edit_user_registration_path %>
<% else %>
<%= link_to 'Sign In', new_user_session_path %>
<%= link_to 'Register', new_user_registration_path %>
<% end %>
</div>

<div class="logo">
<h1><%= link_to 'WikiCode', root_path %></h1>
</div>

</header>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>


<div class="main">
<%= yield %>
</div>
</body>
</html>